root: ./
structure:
  readme: ./en/README.md
  summary: ./en/SUMMARY.md

variants:
  fr:
    root: ./fr
  es:
    root: ./es
  ar:
    root: ./ar
  it:
    root: ./it
  ja:
    root: ./ja
  nl:
    root: ./nl
  ko:
    root: ./ko
  pt:
    root: ./pt
  ru:
    root: ./ru
  zh:
    root: ./zh

redirects:
  previous/page: new/page 