root: ./en
structure:
  readme: README.md
  summary: SUMMARY.md
  languages:
    - en
variants:
  fr: ./fr
  es: ./es
  ar: ./ar
  it: ./it
  ja: ./ja
  nl: ./nl
  ko: ./ko
  pt: ./pt
  ru: ./ru
  zh: ./zh
redirects:
  previous/page: new/page 