---
git-sync:
  enabled: true
  branch: feature/gitbook-integration
  message-prefix: "[GitBook]"
  message-suffix: ""
  protected-files:
    - "**/*.md"
    - ".env"
    - "*.key"
    - "api-keys.json"

theme:
  color: "#3884FF"
  page-backgrounds: true
  layout:
    hideSidebar: false
    hideNavbar: false
    hideSummary: false

plugins:
  - search
  - hints
  - code-blocks

structure:
  langs:
    - en

variants:
  fr:
    name: Français
    path: fr
  es:
    name: Español
    path: es
  ar:
    name: العربية
    path: ar
  it:
    name: Italiano
    path: it
  ja:
    name: 日本語
    path: ja

ignorePatterns:
  - "temp_*"
  - "*.log" 