---
git-sync:
  enabled: true
  branch: feature/gitbook-integration
  message-prefix: "[GitBook]"
  message-suffix: ""
  protected-files:
    - "**/*.md"
    - ".env"
    - "*.key"
    - "api-keys.json"

theme:
  color: "#3884FF"
  page-backgrounds: true
  layout:
    hideSidebar: false
    hideNavbar: false
    hideSummary: false

plugins:
  - search
  - hints
  - code-blocks

structure:
  langs:
    - en
    - fr
    - es
    - ar
    - it
    - ja

languages:
  en:
    name: English
    code: en
  fr:
    name: Français
    code: fr
  es:
    name: Español
    code: es
  ar:
    name: العربية
    code: ar
  it:
    name: Italiano
    code: it
  ja:
    name: 日本語
    code: ja

ignorePatterns:
  - "temp_*"
  - "*.log" 